version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: javahotkey
      SQL_INTERNAL_PORT: 3306
      SQL_CLIENT_PORT: 3306
    volumes:
      - mysql-data:/var/lib/mysql-jhk
    ports:
      - 3306:3306
    expose:
        - 3306
    networks:
      - jhk-network

  phpmyadmin:
    links:
      - db
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - jhk-network

networks:
  jhk-network:


volumes:
  mysql-data:



